name: Perform Code Clean
concurrency: 
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 2 * * *'

jobs:
  clean-code:
    uses: eclipse-platform/eclipse.platform.releng.aggregator/.github/workflows/cleanCode.yml@master
    with:
      author: Eclipse PDE Bot <pde-bot@eclipse.org>
      do-quickfix: false
      do-cleanups: true
      do-manifest: true
      bundle-folders: ui/*/ ua/*/ ds/*/ build/*/ apitools/*/ e4tools/bundles/*/
    secrets:
      token: ${{ secrets.PDE_BOT_PAT }}
