name: HTML Check

on:
  pull_request:
    paths:
      - '**.htm*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6 # Requried will all actions
    - name: Checks HTML5
      uses: Cyb3r-Jak3/html5validator-action@v8.0.0
      with:
        root: /github/workspace/org.eclipse.pde.doc.user
        blacklist: about.html notices.html